name: server

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: pnpm install

      - name: RUN
        run: |-
          export PID=$(lsof -t -i:8080)
          [ "$PID" != "" ] && kill $PID
          RUNNER_TRACKING_ID="" && nohup pnpm start &
